<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Gakuseisean-Ivista-2-Network-Panel-Settings.ico</ApplicationIcon>
	<Version>2.0.0-alpha.2</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DNSetter.Core/**/*.cs;DNSetter.Windows/**/*.cs;tests/**/*.cs" />
    <EmbeddedResource Remove="DNSetter.Core/**/*;DNSetter.Windows/**/*;tests/**/*" />
    <None Remove="DNSetter.Core/**/*;DNSetter.Windows/**/*;tests/**/*" />
    <ProjectReference Include="DNSetter.Core/DNSetter.Core.csproj" />
    <ProjectReference Include="DNSetter.Windows/DNSetter.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Gakuseisean-Ivista-2-Network-Panel-Settings.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>