#nullable enable
namespace DNSetter
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer? components;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            var resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            var toolTip = new ToolTip(components);
            var root = new TableLayoutPanel();
            var header = new TableLayoutPanel();
            var headerText = new TableLayoutPanel();
            var body = new Panel();
            var content = new TableLayoutPanel();
            var adapterCard = new GroupBox();
            var adapterLayout = new TableLayoutPanel();
            var adapterActions = new TableLayoutPanel();
            var stateHeading = new TableLayoutPanel();
            var dnsCard = new GroupBox();
            var dnsLayout = new TableLayoutPanel();
            var addresses = new TableLayoutPanel();
            var primaryField = new TableLayoutPanel();
            var secondaryField = new TableLayoutPanel();
            var dnsActions = new FlowLayoutPanel();
            var toolsCard = new GroupBox();
            var toolsLayout = new TableLayoutPanel();
            var toolsActions = new FlowLayoutPanel();
            var footer = new TableLayoutPanel();
            TitleLabel = new Label();
            VersionLabel = new Label();
            AdapterList = new ComboBox();
            RefreshAdaptersButton = new Button();
            CurrentAdapterDnsLabel = new TextBox();
            AdapterStateLabel = new Label();
            DnsModeLabel = new Label();
            DnsList = new ComboBox();
            DnsTextOne = new TextBox();
            DnsTextTwo = new TextBox();
            SetButton = new Button();
            UnsetDnsButton = new Button();
            AddOrUpdateButton = new Button();
            TestSelectedDnsButton = new Button();
            TestAllDnsListButton = new Button();
            CheckCurrentDnsButton = new Button();
            CheckCensorshipButton = new Button();
            OperationStatusLabel = new Label();
            BusyProgressBar = new ProgressBar();
            linkLabel1 = new LinkLabel();
            linkLabel2 = new LinkLabel();
            SuspendLayout();

            // Docked sections and auto-sized rows keep the form usable at larger text/DPI settings.
            root.Name = "RootLayout";
            root.Dock = DockStyle.Fill;
            root.ColumnCount = 1;
            root.RowCount = 3;
            root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            root.Margin = Padding.Empty;
            root.BackColor = UiTheme.Background;

            header.Name = "Header";
            header.Dock = DockStyle.Fill;
            header.AutoSize = true;
            header.Padding = new Padding(24, 18, 24, 18);
            header.Margin = Padding.Empty;
            header.ColumnCount = 2;
            header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            header.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            header.BackColor = UiTheme.Header;
            headerText.Dock = DockStyle.Fill;
            headerText.AutoSize = true;
            headerText.ColumnCount = 1;
            headerText.Margin = Padding.Empty;
            TitleLabel.Name = "TitleLabel";
            TitleLabel.Text = "DNSetter";
            TitleLabel.AutoSize = true;
            TitleLabel.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
            TitleLabel.ForeColor = UiTheme.HeaderText;
            TitleLabel.Margin = Padding.Empty;
            var subtitle = new Label
            {
                Text = "A clearer view of your network. A simpler way to set DNS.",
                AutoSize = true, Dock = DockStyle.Fill, ForeColor = UiTheme.HeaderMuted, Margin = new Padding(0, 4, 0, 0)
            };
            VersionLabel.Name = "VersionLabel";
            VersionLabel.AutoSize = true;
            VersionLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            VersionLabel.ForeColor = UiTheme.HeaderMuted;
            VersionLabel.Margin = new Padding(16, 10, 0, 0);
            headerText.Controls.Add(TitleLabel, 0, 0);
            headerText.Controls.Add(subtitle, 0, 1);
            header.Controls.Add(headerText, 0, 0);
            header.Controls.Add(VersionLabel, 1, 0);

            body.Name = "ScrollableContent";
            body.Dock = DockStyle.Fill;
            body.AutoScroll = true;
            body.Padding = new Padding(20, 12, 20, 12);
            body.Margin = Padding.Empty;
            content.Name = "ContentLayout";
            content.Dock = DockStyle.Top;
            content.AutoSize = true;
            content.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            content.ColumnCount = 1;
            content.RowCount = 4;
            content.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            content.Margin = Padding.Empty;
            body.Controls.Add(content);

            adapterCard.Name = "AdapterCard";
            adapterCard.Text = "1   Network adapter";
            adapterCard.Dock = DockStyle.Fill;
            adapterCard.AutoSize = true;
            adapterCard.Padding = new Padding(16, 12, 16, 16);
            adapterCard.Margin = new Padding(0, 0, 0, 12);
            adapterCard.BackColor = UiTheme.Surface;
            adapterCard.TabIndex = 0;
            adapterLayout.Dock = DockStyle.Fill;
            adapterLayout.AutoSize = true;
            adapterLayout.ColumnCount = 1;
            adapterLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            adapterLayout.Margin = Padding.Empty;
            adapterActions.Dock = DockStyle.Fill;
            adapterActions.AutoSize = true;
            adapterActions.ColumnCount = 2;
            adapterActions.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            adapterActions.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            adapterActions.Margin = Padding.Empty;
            AdapterList.Name = "AdapterList";
            AdapterList.Dock = DockStyle.Fill;
            AdapterList.DropDownStyle = ComboBoxStyle.DropDownList;
            AdapterList.DropDownWidth = 650;
            AdapterList.Margin = new Padding(0, 3, 12, 3);
            AdapterList.TabIndex = 0;
            AdapterList.AccessibleName = "Network adapter";
            AdapterList.SelectedIndexChanged += AdapterList_SelectedIndexChanged;
            RefreshAdaptersButton.Name = "RefreshAdaptersButton";
            RefreshAdaptersButton.Text = "&Refresh";
            RefreshAdaptersButton.TabIndex = 1;
            RefreshAdaptersButton.Click += RefreshAdaptersButton_Click;
            adapterActions.Controls.Add(AdapterList, 0, 0);
            adapterActions.Controls.Add(RefreshAdaptersButton, 1, 0);
            AdapterStateLabel.Name = "AdapterStateLabel";
            AdapterStateLabel.AutoSize = true;
            AdapterStateLabel.Dock = DockStyle.Fill;
            AdapterStateLabel.ForeColor = UiTheme.Muted;
            AdapterStateLabel.Margin = new Padding(0, 6, 0, 10);
            AdapterStateLabel.Text = "Choose the adapter you want to configure.";
            stateHeading.Dock = DockStyle.Fill;
            stateHeading.AutoSize = true;
            stateHeading.ColumnCount = 2;
            stateHeading.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            stateHeading.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            stateHeading.Margin = Padding.Empty;
            var currentLabel = new Label { Text = "Current IPv4 DNS", AutoSize = true, Margin = new Padding(0, 0, 0, 6) };
            DnsModeLabel.Name = "DnsModeLabel";
            DnsModeLabel.Text = "No adapter selected";
            DnsModeLabel.AutoSize = true;
            DnsModeLabel.ForeColor = UiTheme.Muted;
            DnsModeLabel.Margin = new Padding(12, 0, 0, 6);
            stateHeading.Controls.Add(currentLabel, 0, 0);
            stateHeading.Controls.Add(DnsModeLabel, 1, 0);
            CurrentAdapterDnsLabel.Name = "CurrentAdapterDnsLabel";
            CurrentAdapterDnsLabel.Dock = DockStyle.Fill;
            CurrentAdapterDnsLabel.Multiline = true;
            CurrentAdapterDnsLabel.ReadOnly = true;
            CurrentAdapterDnsLabel.ScrollBars = ScrollBars.Vertical;
            CurrentAdapterDnsLabel.Height = 54;
            CurrentAdapterDnsLabel.Margin = Padding.Empty;
            CurrentAdapterDnsLabel.Font = new Font("Consolas", 10F);
            CurrentAdapterDnsLabel.BackColor = UiTheme.ReadOnly;
            CurrentAdapterDnsLabel.AccessibleName = "Current IPv4 DNS servers, read only";
            CurrentAdapterDnsLabel.TabIndex = 2;
            adapterLayout.Controls.Add(adapterActions, 0, 0);
            adapterLayout.Controls.Add(AdapterStateLabel, 0, 1);
            adapterLayout.Controls.Add(stateHeading, 0, 2);
            adapterLayout.Controls.Add(CurrentAdapterDnsLabel, 0, 3);
            adapterCard.Controls.Add(adapterLayout);

            dnsCard.Name = "DnsSettingsCard";
            dnsCard.Text = "2   DNS settings";
            dnsCard.Dock = DockStyle.Fill;
            dnsCard.AutoSize = true;
            dnsCard.Padding = new Padding(16, 12, 16, 16);
            dnsCard.Margin = new Padding(0, 0, 0, 12);
            dnsCard.BackColor = UiTheme.Surface;
            dnsCard.TabIndex = 1;
            dnsLayout.Dock = DockStyle.Fill;
            dnsLayout.AutoSize = true;
            dnsLayout.ColumnCount = 1;
            dnsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            dnsLayout.Margin = Padding.Empty;
            var providerLabel = new Label { Text = "DNS provider", AutoSize = true, Margin = new Padding(0, 0, 0, 6) };
            DnsList.Name = "DnsList";
            DnsList.Dock = DockStyle.Fill;
            DnsList.DropDownStyle = ComboBoxStyle.DropDownList;
            DnsList.Margin = new Padding(0, 0, 0, 12);
            DnsList.TabIndex = 0;
            DnsList.AccessibleName = "DNS provider";
            DnsList.SelectedIndexChanged += DnsList_SelectedIndexChanged;
            addresses.Dock = DockStyle.Fill;
            addresses.AutoSize = true;
            addresses.ColumnCount = 2;
            addresses.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            addresses.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            addresses.Margin = Padding.Empty;
            addresses.TabIndex = 1;
            primaryField.Dock = DockStyle.Fill;
            primaryField.AutoSize = true;
            primaryField.ColumnCount = 1;
            primaryField.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            primaryField.Margin = new Padding(0, 0, 8, 0);
            secondaryField.Dock = DockStyle.Fill;
            secondaryField.AutoSize = true;
            secondaryField.ColumnCount = 1;
            secondaryField.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            secondaryField.Margin = new Padding(8, 0, 0, 0);
            secondaryField.TabIndex = 1;
            var primaryLabel = new Label { Text = "Primary DNS", AutoSize = true, Margin = new Padding(0, 0, 0, 6) };
            var secondaryLabel = new Label { Text = "Secondary DNS (optional)", AutoSize = true, Margin = new Padding(0, 0, 0, 6) };
            DnsTextOne.Name = "DnsTextOne";
            DnsTextOne.Dock = DockStyle.Fill;
            DnsTextOne.Font = new Font("Consolas", 11F);
            DnsTextOne.PlaceholderText = "e.g. 1.1.1.1";
            DnsTextOne.AccessibleName = "Primary IPv4 DNS server";
            DnsTextOne.Margin = Padding.Empty;
            DnsTextOne.TextChanged += DnsInput_TextChanged;
            DnsTextTwo.Name = "DnsTextTwo";
            DnsTextTwo.Dock = DockStyle.Fill;
            DnsTextTwo.Font = new Font("Consolas", 11F);
            DnsTextTwo.PlaceholderText = "e.g. 1.0.0.1";
            DnsTextTwo.AccessibleName = "Secondary IPv4 DNS server, optional";
            DnsTextTwo.Margin = Padding.Empty;
            DnsTextTwo.TextChanged += DnsInput_TextChanged;
            primaryField.Controls.Add(primaryLabel, 0, 0);
            primaryField.Controls.Add(DnsTextOne, 0, 1);
            secondaryField.Controls.Add(secondaryLabel, 0, 0);
            secondaryField.Controls.Add(DnsTextTwo, 0, 1);
            addresses.Controls.Add(primaryField, 0, 0);
            addresses.Controls.Add(secondaryField, 1, 0);
            var scopeNote = new Label
            {
                Text = "Changes apply to IPv4 DNS on the selected adapter. IPv6 is unchanged.",
                AutoSize = true, Dock = DockStyle.Fill, ForeColor = UiTheme.Muted, Margin = new Padding(0, 10, 0, 10)
            };
            dnsActions.Dock = DockStyle.Fill;
            dnsActions.AutoSize = true;
            dnsActions.WrapContents = true;
            dnsActions.Margin = Padding.Empty;
            dnsActions.TabIndex = 2;
            SetButton.Name = "SetButton";
            SetButton.Text = "&Apply DNS";
            SetButton.TabIndex = 0;
            SetButton.Click += SetButton_Click;
            UnsetDnsButton.Name = "UnsetDnsButton";
            UnsetDnsButton.Text = "&Automatic DNS";
            UnsetDnsButton.TabIndex = 1;
            UnsetDnsButton.Click += UnsetDnsButton_Click;
            AddOrUpdateButton.Name = "AddOrUpdateButton";
            AddOrUpdateButton.Text = "Sa&ve preset";
            AddOrUpdateButton.TabIndex = 2;
            AddOrUpdateButton.Click += AddOrUpdateButton_Click;
            dnsActions.Controls.AddRange([SetButton, UnsetDnsButton, AddOrUpdateButton]);
            dnsLayout.Controls.Add(providerLabel, 0, 0);
            dnsLayout.Controls.Add(DnsList, 0, 1);
            dnsLayout.Controls.Add(addresses, 0, 2);
            dnsLayout.Controls.Add(scopeNote, 0, 3);
            dnsLayout.Controls.Add(dnsActions, 0, 4);
            dnsCard.Controls.Add(dnsLayout);

            toolsCard.Name = "ToolsCard";
            toolsCard.Text = "Network tools";
            toolsCard.Dock = DockStyle.Fill;
            toolsCard.AutoSize = true;
            toolsCard.Padding = new Padding(16, 12, 16, 16);
            toolsCard.Margin = new Padding(0, 0, 0, 12);
            toolsCard.BackColor = UiTheme.Surface;
            toolsCard.TabIndex = 2;
            toolsLayout.Dock = DockStyle.Fill;
            toolsLayout.AutoSize = true;
            toolsLayout.ColumnCount = 1;
            toolsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            toolsLayout.Margin = Padding.Empty;
            toolsActions.Dock = DockStyle.Fill;
            toolsActions.AutoSize = true;
            toolsActions.WrapContents = true;
            toolsActions.Margin = Padding.Empty;
            TestSelectedDnsButton.Name = "TestSelectedDnsButton";
            TestSelectedDnsButton.Text = "&Ping DNS";
            TestSelectedDnsButton.TabIndex = 0;
            TestSelectedDnsButton.Click += TestSelectedDnsButton_Click;
            TestAllDnsListButton.Name = "TestAllDnsListButton";
            TestAllDnsListButton.Text = "&Test all presets";
            TestAllDnsListButton.TabIndex = 1;
            TestAllDnsListButton.Click += TestAllDnsListButton_Click;
            CheckCurrentDnsButton.Name = "CheckCurrentDnsButton";
            CheckCurrentDnsButton.Text = "Adapter &details";
            CheckCurrentDnsButton.TabIndex = 2;
            CheckCurrentDnsButton.Click += CheckCurrentDnsButton_Click;
            CheckCensorshipButton.Name = "CheckCensorshipButton";
            CheckCensorshipButton.Text = "Site reac&hability";
            CheckCensorshipButton.TabIndex = 3;
            CheckCensorshipButton.Click += CheckCensorshipButton_Click;
            toolsActions.Controls.AddRange([TestSelectedDnsButton, TestAllDnsListButton, CheckCurrentDnsButton, CheckCensorshipButton]);
            toolsLayout.Controls.Add(toolsActions, 0, 0);
            var pingNote = new Label
            {
                Text = "Ping measures ICMP latency; a timeout does not prove that a DNS server is unavailable.",
                AutoSize = true, Dock = DockStyle.Fill, ForeColor = UiTheme.Muted, Margin = new Padding(0, 10, 0, 0)
            };
            toolsLayout.Controls.Add(pingNote, 0, 1);
            toolsCard.Controls.Add(toolsLayout);

            OperationStatusLabel.Name = "OperationStatusLabel";
            OperationStatusLabel.Text = "Select an adapter to get started.";
            OperationStatusLabel.AutoSize = true;
            OperationStatusLabel.Dock = DockStyle.Fill;
            OperationStatusLabel.Padding = new Padding(12);
            OperationStatusLabel.Margin = Padding.Empty;
            OperationStatusLabel.BackColor = UiTheme.ReadOnly;
            OperationStatusLabel.ForeColor = UiTheme.Text;
            OperationStatusLabel.AccessibleName = "Operation result";
            OperationStatusLabel.TabStop = false;
            content.Controls.Add(adapterCard, 0, 0);
            content.Controls.Add(dnsCard, 0, 1);
            content.Controls.Add(toolsCard, 0, 2);
            content.Controls.Add(OperationStatusLabel, 0, 3);

            footer.Dock = DockStyle.Fill;
            footer.AutoSize = true;
            footer.ColumnCount = 3;
            footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            footer.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            footer.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            footer.Margin = Padding.Empty;
            footer.Padding = new Padding(24, 8, 24, 10);
            BusyProgressBar.Name = "BusyProgressBar";
            BusyProgressBar.Style = ProgressBarStyle.Marquee;
            BusyProgressBar.MarqueeAnimationSpeed = 30;
            BusyProgressBar.Size = new Size(120, 12);
            BusyProgressBar.Anchor = AnchorStyles.Left;
            BusyProgressBar.Visible = false;
            linkLabel1.Name = "linkLabel1";
            linkLabel1.Text = "GitHub";
            linkLabel1.AutoSize = true;
            linkLabel1.Margin = new Padding(12, 0, 0, 0);
            linkLabel1.LinkClicked += linkLabel1_LinkClicked;
            linkLabel2.Name = "linkLabel2";
            linkLabel2.Text = "Mehrdad32";
            linkLabel2.AutoSize = true;
            linkLabel2.Margin = new Padding(20, 0, 0, 0);
            linkLabel2.LinkClicked += linkLabel2_LinkClicked;
            footer.Controls.Add(BusyProgressBar, 0, 0);
            footer.Controls.Add(linkLabel1, 1, 0);
            footer.Controls.Add(linkLabel2, 2, 0);
            root.Controls.Add(header, 0, 0);
            root.Controls.Add(body, 0, 1);
            root.Controls.Add(footer, 0, 2);

            toolTip.SetToolTip(UnsetDnsButton, "Use automatically assigned DNS. This does not restore a previous manual preset.");
            toolTip.SetToolTip(AddOrUpdateButton, "Save these addresses as a preset without changing your network.");
            toolTip.SetToolTip(RefreshAdaptersButton, "Reload adapters and the selected adapter's current DNS.");
            toolTip.SetToolTip(CurrentAdapterDnsLabel, "Current IPv4 DNS reported by Windows. Select and copy with Ctrl+C.");
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(760, 748);
            MinimumSize = new Size(680, 600);
            Font = new Font("Segoe UI", 10F);
            BackColor = UiTheme.Background;
            ForeColor = UiTheme.Text;
            Controls.Add(root);
            Icon = (Icon?)resources.GetObject("$this.Icon");
            Name = "MainForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "DNSetter";
            Load += MainForm_Load;
            ResumeLayout(true);
        }

        private Label TitleLabel = null!;
        private Label VersionLabel = null!;
        private ComboBox AdapterList = null!;
        private Button RefreshAdaptersButton = null!;
        private TextBox CurrentAdapterDnsLabel = null!;
        private Label AdapterStateLabel = null!;
        private Label DnsModeLabel = null!;
        private ComboBox DnsList = null!;
        private TextBox DnsTextOne = null!;
        private TextBox DnsTextTwo = null!;
        private Button SetButton = null!;
        private Button AddOrUpdateButton = null!;
        private Button TestSelectedDnsButton = null!;
        private Button TestAllDnsListButton = null!;
        private Button UnsetDnsButton = null!;
        private Button CheckCurrentDnsButton = null!;
        private Button CheckCensorshipButton = null!;
        private Label OperationStatusLabel = null!;
        private ProgressBar BusyProgressBar = null!;
        private LinkLabel linkLabel1 = null!;
        private LinkLabel linkLabel2 = null!;
    }
}
