name: Build and Release DNSetter

on:
  push:
    tags:
      - 'v*'  # triggers only when pushing a tag like v1.0, v1.1 etc.

jobs:
  build:
    name: Build and Release for Windows
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [win-x86, win-x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish ${{ matrix.arch }}
      run: dotnet publish -c Release -r ${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=false -o publish/${{ matrix.arch }}

    - name: Zip output
      run: Compress-Archive -Path publish/${{ matrix.arch }} -DestinationPath DNSetter-${{ matrix.arch }}.zip

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          DNSetter-${{ matrix.arch }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
